version: '3.8'

networks:
  laravel:
  notify_rabbitmq:
    driver: bridge

services:
  notify_nginx:
    image: nginx:stable-alpine
    container_name: notify_nginx
    ports:
      - 8088:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - notify_php
      - notify_mysql
    networks:
      - laravel

  notify_rabbitmq:
    image: rabbitmq:3-management
    hostname: 'mabbit'
    container_name: rabbitmq_management
    environment:
      - RABBITMQ_DEFAULT_USER = ygkybebp
      - RABBITMQ_DEFAULT_PASS = Fglat0CpQ1T7M0BW82J8Eyln36cZWxoh
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./src:/var/lib/rabbitmq/mnesia/"
    restart: always
    networks:
      - notify_rabbitmq

  notify_mysql:
    image: mysql:8.0
    container_name: notify_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    environment:
      MYSQL_DATABASE: jvconsult
      MYSQL_USER: root
      MYSQL_PASSWORD: arthur
      MYSQL_ROOT_PASSWORD: arthur
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - ./mysql:/var/lib/mysql

  notify_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notify_php
    working_dir: /var/www
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    ports:
      - 9001:9000
    depends_on:
      - notify_mysql
